In [175]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets
import scipy.optimize as so

In [176]:
f=pd.read_csv(r'ASDBinary.csv')
f=f.values

In [177]:
print(f)

[[22  1  0  0  1  0  5  0]
 [22  1  0  0  2  0  5  0]
 [22  1  0  0  2  0  5  0]
 [24  1  0  0  1  0  7  1]
 [27  1  0  0  0  0  5  0]
 [23  1  1  0  1  0  5  0]
 [22  1  0  0  2  0  4  0]
 [35  1  0  0  1  0  7  1]
 [69  0  0  0  2  0  0  0]
 [50  1  0  1  2  0  7  1]
 [21  0  0  0  0  0  6  1]
 [21  1  0  0  0  0  7  1]
 [22  1  0  0  0  0  5  0]
 [47  1  1  0  0  0  7  1]
 [30  1  0  0  0  0  6  1]
 [32  0  0  0  1  0  5  0]
 [52  1  0  0  1  0  8  1]
 [21  1  0  0  0  0  7  1]
 [35  1  0  0  0  0  7  1]
 [21  1  0  0  0  0  7  1]
 [21  1  0  0  0  0  8  1]
 [23  1  0  0  2  0  8  1]
 [22  1  0  0  0  0  5  0]
 [20  1  0  0  0  0  6  1]
 [21  1  0  0  0  0  8  1]
 [22  0  0  0  0  0  8  1]
 [21  1  0  0  0  0  8  1]
 [46  0  0  0  0  1  8  1]
 [18  1  0  0  1  0  6  1]
 [15  1  0  0  0  0  7  1]
 [48  1  1  0  1  0  5  0]
 [20  1  0  0  0  0  8  1]
 [20  1  0  0  0  0  7  1]
 [20  0  0  0  0  0  6  1]
 [22  0  0  0  0  0  6  1]
 [20  1  0  0  0  0  6  1]
 [21  0  0  0  0  0  8  1]
 

In [178]:
X=f[:,6:7]
y = (f[:,6:7] != 0) * 1

In [179]:
class LogisticRegression:
    def __init__(self,lr=0.01, num_iter=100000, fit_intercept=True, verbose=False):
        self.lr = lr
        self.num_iter = num_iter
        self.fit_intercept = fit_intercept
        self.verbose = verbose
    
    def __add_intercept(X):
        intercept = np.ones((X.shape[0], 1))
        return np.concatenate((intercept, X), axis=1)
    
    def __sigmoid( z):
        return 1 / (1 + np.exp(-z))
    def __loss(self, h, y):
        return (-y * np.log(h) - (1 - y) * np.log(1 - h)).mean()
    
    def fit( X, y):
        if self.fit_intercept:
            X = self.__add_intercept(X)
        
        # weights initialization
        self.theta = np.zeros(X.shape[1])
        
        for i in range(self.num_iter):
            z = np.dot(X, self.theta)
            h = self.__sigmoid(z)
            gradient = np.dot(X.T, (h - y)) / y.size
            self.theta -= self.lr * gradient
            
            z = np.dot(X, self.theta)
            h = self.__sigmoid(z)
            loss = self.__loss(h, y)
                
            if(self.verbose ==True and i % 10000 == 0):
                print(f'loss: {loss} \t')
    
    def predict_prob( X):
        if self.fit_intercept:
            X = self.__add_intercept(X)
        return self.__sigmoid(np.dot(X, self.theta))
    
    def predict(X):
        return self.predict_prob(X).round()

In [180]:
model = LogisticRegression(lr=0.1, num_iter=300000)
preds = model.predict(X)
(preds == y).mean()

TypeError: predict() takes 1 positional argument but 2 were given